function hp = ssldrawmesh(T,varargin)
%SSLDRAWMESH Draw a triangular mesh.
%   H = SSLDRAWMESH(T) draws the triangular mesh model given by T;
%   T is an SSL mesh struct generated by SSLMESHSTRUCT;
%   H is the handle to the drawn patch object.
%
%   See also SSLMESHSTRUCT, SSLISMESH.

% Siyi Deng; 03-01-2011; 07-11-2011;

if nargin < 3, varargin = {}; end
hp = patch('faces',T.Face,'vertices',T.Vertex,...
    'facecolor',[.6 .75 .9],'edgecolor','w',varargin{:});
axis(ancestor(hp,'axes'),'equal','vis3d','off');
end % SSLDRAWMESH;

